config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end

  resources :users do
    collection do
      post :import
    end
  end

  root to: "forum_threads#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require 'csv'


class User < ActiveRecord::Base
  # validations or associations here

  devise :database_authenticatable, :registerable, :recoverable, :rememberable

  has_many :forum_threads
  has_many :forum_posts

  def self.import(file)
        counter = 0

    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      user = User.assign_from_row(row)
      if user.save
        counter += 1 
      else
        puts "#{user.email} - #{user.errors.full_messages.join(",")}"
      end
    end

    counter
  end

  def self.assign_from_row(row)
    user = User.where(email: row[:email]).first_or_initialize
    user.assign_attributes row.to_hash.slice(:first_name, :last_name)
    user
  end

  def self.to_csv
    attributes = %w{id email first_name last_name}
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  def name
    if deleted_at?
      "Deleted User"
    else
      "#{first_name} #{last_name}"
    end
  end
end

app/models/user/import.rb
class User::Import
  include ActiveModel::Model
  attr_accessor :file, :imported_count

    def self.model_name
    ActiveModel::Name.new(self, nil, "User::Import")
  end

  def process!
    errors.add(:base, "ERROR!")
  end

  def save
    process!
    errors.none?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.expect(contact: [ :name, :email ])
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  def index
    @forum_threads = ForumThread.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @import = User::Import.new
  end

  #   respond_to do |format|
  #     format.html
  #     format.csv { send_data @users.to_csv, filename: "users-#{Date.today}" }
  #   end
  # end
  
def import
  if params[:user_import].present?
    file = params[:user_import][:file]
    count = User.import(file)
    redirect_to users_path, notice: "Imported #{count} users"
  else
    redirect_to users_path, notice: "Please select a CSV file to upload."
  end
end

  

    def user_import_params
      params.require(:user_import).permit(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<h1 class="page-title">Editing contact</h1>

<div class="contact-form">
  <%= render "form", contact: @contact %>
</div>

<br>

<div class="nav-links">
  <%= link_to "Show this contact", @contact, class: "btn btn-primary" %> |
  <%= link_to "Back to contacts", contacts_path, class: "btn btn-secondary" %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contacts" %>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/forum_threads/index.html.erb
<!-- app/views/forum_threads/index.html.erb -->

<h1>Forum Threads</h1>

<ul>
  <% @forum_threads.each do |thread| %>
    <li><%= thread.title %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <title><%= content_for(:title) || "Csv Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Full Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= "#{user.first_name} #{user.last_name}" %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h2>Import Users from CSV</h2>


<%= form_for @import, url: import_users_path, multipart: true do |f| %>
  <% if @import.errors.any? %>
    <div class="alert alert-error">
      <% @import.errors.full_messages.each do |msg| %>
        <div><%= msg %></div>
      <% end %>
      </div>
      <% end %>

  <%= f.file_field :file %>
  <%= f.submit "Upload" %>
  <% end %>